id: feather
name: Feather Icons
description: Simply beautiful open source icons
type: git

git:
  repo: feathericons/feather
  branch: main
  depth: 1
  sparse_paths:
    - icons/

license:
  spdx: MIT
  attribution_required: false
  commercial_ok: true
  modification_ok: true
  share_alike: false

paths:
  - pattern: "icons/*.svg"
    format: svg
    tags: [icon, ui, minimal, outline]

metadata:
  homepage: https://feathericons.com
  icon_count: 280
  styles: [outline]
  stroke_width: 2
